#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "========================================"
echo "  axolLoop DevContainer セットアップ"
echo "========================================"
echo ""

# インスタンス番号の入力
while true; do
  read -p "インスタンス番号を入力してください (1-8): " INSTANCE
  if [[ "$INSTANCE" =~ ^[1-8]$ ]]; then
    break
  fi
  echo "エラー: 1〜8 の数値を入力してください"
done

# ポートオフセット計算
OFFSET=$(( (INSTANCE - 1) * 10 ))
AL_PORT=$(( 29001 + OFFSET ))
ALDB_PORT=$(( 29002 + OFFSET ))
SMTPAL_PORT=$(( 29003 + OFFSET ))
S3ALTAL_PORT=$(( 29004 + OFFSET ))
ALREDIS_PORT=$(( 29005 + OFFSET ))
S3ALTAL_API_PORT=$(( 29006 + OFFSET ))

echo ""
echo "インスタンス番号: $INSTANCE (offset: +$OFFSET)"
echo "ポート割り当て:"
echo "  al (NestJS/Nuxt):  $AL_PORT"
echo "  aldb (MySQL):      $ALDB_PORT"
echo "  smtpal (Mailpit):  $SMTPAL_PORT"
echo "  s3altal (MinIO):   $S3ALTAL_PORT"
echo "  alredis (Redis):   $ALREDIS_PORT"
echo "  s3altal API:       $S3ALTAL_API_PORT"
echo ""

# .devcontainer/.env の生成
cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by make setup (instance: $INSTANCE)
AL_PORT=$AL_PORT
ALDB_PORT=$ALDB_PORT
SMTPAL_PORT=$SMTPAL_PORT
S3ALTAL_PORT=$S3ALTAL_PORT
ALREDIS_PORT=$ALREDIS_PORT
S3ALTAL_API_PORT=$S3ALTAL_API_PORT
EOF

echo "生成: .devcontainer/.env"

# プロジェクトルートの .env の生成
cat > "$PROJECT_DIR/.env" <<EOF
# Auto-generated by make setup (instance: $INSTANCE)
# axolLoop 環境変数

# アプリケーション
NODE_ENV=development
APP_PORT=3000

# データベース (MySQL)
DATABASE_URL=mysql://axolloop:axolloop@aldb:3306/axolloop
DB_HOST=aldb
DB_PORT=3306
DB_USER=axolloop
DB_PASSWORD=axolloop
DB_NAME=axolloop

# Redis (BullMQ / キャッシュ)
REDIS_URL=redis://alredis:6379
REDIS_HOST=alredis
REDIS_PORT=6379

# メール (Mailpit)
MAIL_HOST=smtpal
MAIL_PORT=1025
MAIL_FROM=noreply@axolloop.local

# S3 (MinIO)
S3_ENDPOINT=http://s3altal:9000
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=minioadmin
S3_BUCKET=axolloop
S3_REGION=ap-northeast-1

# DevContainer ポート（ホスト側）
AL_PORT=$AL_PORT
ALDB_PORT=$ALDB_PORT
SMTPAL_PORT=$SMTPAL_PORT
S3ALTAL_PORT=$S3ALTAL_PORT
ALREDIS_PORT=$ALREDIS_PORT
S3ALTAL_API_PORT=$S3ALTAL_API_PORT
EOF

echo "生成: .env"

# socat-forwards.sh の生成
cat > "$SCRIPT_DIR/socat-forwards.sh" <<EOF
#!/bin/bash
# Auto-generated by make setup (instance: $INSTANCE)
# app コンテナ内のポートフォワード設定

# MySQL
socat TCP-LISTEN:$ALDB_PORT,fork TCP:aldb:3306 &

# Redis
socat TCP-LISTEN:$ALREDIS_PORT,fork TCP:alredis:6379 &

# Mailpit SMTP
socat TCP-LISTEN:$SMTPAL_PORT,fork TCP:smtpal:8025 &

# MinIO API
socat TCP-LISTEN:$S3ALTAL_API_PORT,fork TCP:s3altal:9000 &

echo "socat ポートフォワード起動完了"
EOF

chmod +x "$SCRIPT_DIR/socat-forwards.sh"
echo "生成: .devcontainer/socat-forwards.sh"

echo ""
echo "========================================"
echo "  セットアップ完了!"
echo "========================================"
echo ""
echo "次のステップ:"
echo "  1. VS Code でこのディレクトリを開く"
echo "  2. コマンドパレット > 'Dev Containers: Reopen in Container'"
echo ""
echo "ホストからのログイン:"
echo "  ./devlogin"
echo ""
