#!/bin/bash
# Auto-generated by make setup (instance: __INSTANCE__)
# app コンテナ内のポートフォワード設定

# MySQL
socat TCP-LISTEN:__ALDB_PORT__,fork TCP:aldb:3306 &

# Redis
socat TCP-LISTEN:__ALREDIS_PORT__,fork TCP:alredis:6379 &

# Mailpit SMTP
socat TCP-LISTEN:__SMTPAL_PORT__,fork TCP:smtpal:8025 &

# MinIO API
socat TCP-LISTEN:__S3ALTAL_API_PORT__,fork TCP:s3altal:9000 &

echo "socat ポートフォワード起動完了"
